development:
  adapter: mysql2
  encoding: utf8
  database: sample_development
  username: sampleUser
  password: p@$$w0rd!
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: sample_test
  username: sampleUserTest
  password: p@$$w0rd!
  host: 127.0.0.1
  port: 3306
